version: '3'
services:
  api:
    container_name: jeffqevimage
    restart: always
    image: "jeffqev/go-actions:$BUILD_TAG"
    ports:
      - "1518:1323"
    networks:
      - goactions
networks:
  goactions:
