name: test

on:
  push:
    branches:
      - "main"

jobs:
  different-test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
         go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Testing APP
        run: go test ./...
      - uses: actions/checkout@master
      - name: build and push to dockerhub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tags: ${{ github.sha }}
      - name: Deploy with ssh
        uses: cross-the-world/ssh-pipeline@master
        env:
          SHA: ${{ github.sha }}
          PATHDC: ${{ secrets.DOCKER_COMPOSE_PATH }}
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          script: |
            cd $PATHDC
            export BUILD_TAG=$SHA
            sh script.sh
            